name: Build & Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'oauth2-microservice/**'
      - '.github/workflows/build-docker.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./oauth2-microservice
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/oauth2-service:latest
