# CI workflow for building Java callouts
name: Build Java Callouts

on:
  push:
    paths:
      - 'java-callouts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Build all JARs
        run: mvn clean install -f java-callouts/token-generator/pom.xml
