# CD workflow for deploying apiproxy
name: Deploy Apigee Proxy

on:
  push:
    paths:
      - 'apiproxy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Apigee
        run: |
          npm install -g apigeetool
          apigeetool deployproxy -n custom-oauth2-proxy \
            -o ${{ secrets.APIGEE_ORG }} -e ${{ secrets.APIGEE_ENV }} \
            -u ${{ secrets.APIGEE_USER }} -p ${{ secrets.APIGEE_PASSWORD }} \
            -d apiproxy
